# Generated by Django 5.2.8 on 2025-12-09 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_alter_noticia_descripcion_alter_noticia_titulo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallike',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='social/imagenes/'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
