# Generated by Django 5.2.8 on 2025-12-09 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_alter_sociallike_options_alter_socialpost_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialcomentario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sociallike',
            options={},
        ),
        migrations.AlterModelOptions(
            name='socialpost',
            options={},
        ),
        migrations.RenameField(
            model_name='socialcomentario',
            old_name='creado',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='socialpost',
            old_name='creado',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='sociallike',
            name='creado',
        ),
        migrations.AlterField(
            model_name='socialcomentario',
            name='texto',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='social/img/'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='titulo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='social/video/'),
        ),
    ]
