# Generated by Django 5.2.8 on 2025-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_alter_socialcomentario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='en_logros',
            field=models.BooleanField(default=False),
        ),
    ]
