# Generated by Django 5.2.8 on 2025-12-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_socialpost_en_logros'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='contacto2_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='contacto2_relacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='contacto2_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default='perfiles/perfil.png', upload_to='perfiles/'),
        ),
    ]
