# Generated by Django 5.2.8 on 2025-12-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_perfil_contacto2_nombre_perfil_contacto2_relacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='texto_logro',
            field=models.TextField(blank=True, help_text='Descripción breve del logro institucional', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='intranet.cargo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='estamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='intranet.estamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='perfiles/perfil.png', upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='unidad_fiscalia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='intranet.unidadfiscalia'),
        ),
    ]
