# Generated by Django 5.2.8 on 2025-12-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_socialpost_texto_logro_alter_perfil_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='run',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='RUN'),
        ),
    ]
