# Generated by Django 5.2.8 on 2026-01-06 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_unidadfiscalia_estado_alter_documento_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='capacitaciones/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='intranet.perfil')),
            ],
        ),
    ]
