# Generated by Django 5.2.8 on 2026-01-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_capacitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('Prensa', 'Prensa'), ('Nosotros', 'Nosotros'), ('Concursos', 'Concursos'), ('Comunidad', 'Comunidad'), ('Campañas', 'Campañas')], max_length=100),
        ),
    ]
