# Generated by Django 5.2.8 on 2026-01-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_alter_noticia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('REGLAMENTOS', 'Reglamentos, Protocolos e Instructivos'), ('PROCESOS', 'Procesos de Trabajo'), ('BIENESTAR', 'Bienestar')], default='REGLAMENTOS', max_length=20),
        ),
    ]
