# Generated by Django 5.2.8 on 2026-01-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0013_documento_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('REGLAMENTOS', 'Reglamentos, Protocolos e Instructivos'), ('PROCESOS', 'Procesos de Trabajo'), ('BIENESTAR', 'Bienestar')], max_length=20),
        ),
    ]
