# Generated by Django 5.2.8 on 2026-01-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0015_categoriadocumento_documentocomite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriadocumento',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='documentocomite',
            options={'ordering': ['-fecha_subida']},
        ),
        migrations.AlterField(
            model_name='categoriadocumento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriadocumento',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
