# Generated by Django 5.2.8 on 2026-01-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0016_alter_categoriadocumento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('Prensa', 'Prensa'), ('Nosotros', 'Nosotros'), ('Concursos', 'Concursos'), ('Comunidad', 'Comunidad'), ('Campañas', 'Campañas'), ('Editorial', 'Editorial')], max_length=100),
        ),
    ]
