# Generated by Django 5.2.7 on 2026-01-22 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0019_delete_comisaria_delete_fiscalia_delete_juzgado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('Empresa', 'Empresa'), ('Tecnología', 'Tecnología'), ('Proyectos', 'Proyectos'), ('Clientes', 'Clientes'), ('Comunicados', 'Comunicados')], max_length=100),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='intranet.area')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='intranet.area')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='intranet.rol')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
