# Generated by Django 5.2.7 on 2026-01-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0020_tipocontrato_alter_noticia_categoria_area_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='area',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='superior',
        ),
        migrations.DeleteModel(
            name='TipoContrato',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
