# Generated by Django 5.2.7 on 2026-01-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0025_proyecto_imagen_proyecto_url_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, choices=[('Disponible', 'Disponible'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado'), ('Latente', 'Latente')], default='Disponible', max_length=50),
        ),
    ]
